/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_sahorycano;

import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sahory
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jD_Modificar = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Nombre_Programa1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Puntuacion1 = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        Año_Lanzamiento1 = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        Tipodeprograma1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        Genero_programa1 = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        AgregarSerVivo1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Nombre_Programa = new javax.swing.JTextField();
        Puntuacion = new javax.swing.JFormattedTextField();
        Año_Lanzamiento = new javax.swing.JFormattedTextField();
        Genero_programa = new javax.swing.JComboBox<>();
        AgregarSerVivo = new javax.swing.JButton();
        Tipodeprograma = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ModificarAtributo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaClauModificar = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaClauEliminar = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        EliminarSerVivo = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        CBProgramas = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaDatosClau = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        GuardarArchivo = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextAreaArchivo = new javax.swing.JTextArea();
        CargarArchivo = new javax.swing.JButton();

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Strawberry Blossom", 0, 48)); // NOI18N
        jLabel12.setText("Agregar Programa");

        jLabel13.setText("Nombre: ");

        jLabel14.setText("Puntuación");

        Puntuacion1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel15.setText("Año  de lanzamiento");

        Año_Lanzamiento1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel16.setText("Tipo");

        Tipodeprograma1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anime", "serie", "documental", "película" }));

        jLabel17.setText("Genero");

        Genero_programa1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comedia", "romance", "terror", "SyFy", "Suspenso", "accion" }));

        jPanel10.setBackground(new java.awt.Color(0, 255, 204));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(0, 255, 204));

        AgregarSerVivo1.setBackground(new java.awt.Color(0, 255, 204));
        AgregarSerVivo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AgregarSerVivo1.setText("Modificar Programa");
        AgregarSerVivo1.setBorder(null);
        AgregarSerVivo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarSerVivo1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addComponent(AgregarSerVivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AgregarSerVivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Puntuacion1)
                            .addComponent(Año_Lanzamiento1)
                            .addComponent(Genero_programa1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nombre_Programa1)
                            .addComponent(Tipodeprograma1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(213, 213, 213))
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Nombre_Programa1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Puntuacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Año_Lanzamiento1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Tipodeprograma1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(Genero_programa1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jD_ModificarLayout = new javax.swing.GroupLayout(jD_Modificar.getContentPane());
        jD_Modificar.getContentPane().setLayout(jD_ModificarLayout);
        jD_ModificarLayout.setHorizontalGroup(
            jD_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jD_ModificarLayout.setVerticalGroup(
            jD_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Strawberry Blossom", 0, 50)); // NOI18N
        jLabel1.setText("My ClaudiList");

        jPanel3.setBackground(new java.awt.Color(0, 204, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Agregar Programa");

        jLabel3.setText("Nombre: ");

        jLabel4.setText("Puntuación");

        jLabel5.setText("Año  de lanzamiento");

        jLabel6.setText("Tipo");

        jLabel7.setText("Genero");

        Puntuacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        Año_Lanzamiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        Genero_programa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comedia", "romance", "terror", "SyFy", "Suspenso", "accion" }));

        AgregarSerVivo.setText("Agregar Programa");
        AgregarSerVivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarSerVivoMouseClicked(evt);
            }
        });

        Tipodeprograma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anime", "serie", "documental", "película" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Puntuacion)
                    .addComponent(Año_Lanzamiento)
                    .addComponent(Genero_programa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Nombre_Programa)
                    .addComponent(Tipodeprograma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 282, Short.MAX_VALUE)
                .addComponent(AgregarSerVivo)
                .addGap(252, 252, 252))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Nombre_Programa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Puntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Año_Lanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Tipodeprograma, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Genero_programa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AgregarSerVivo, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agregar Programa", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("Modificar Programa");

        ModificarAtributo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Poder", "Años", "Planeta de procedencia", "Raza" }));
        ModificarAtributo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ModificarAtributoItemStateChanged(evt);
            }
        });

        TablaClauModificar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Puntuación", "Año de lanzamiento", "Tipo ", "Genero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablaClauModificar);

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("* Seleccione una fila para poder modificar un atributo *");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(ModificarAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(jLabel8))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(jLabel9)))
                        .addGap(0, 132, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(ModificarAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar Programa", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        TablaClauEliminar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Puntuación", "Año de lanzamiento", "Tipo", "Género"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaClauEliminar);

        jLabel10.setText("Eliminar Programa");

        EliminarSerVivo.setText("Eliminar Programa");
        EliminarSerVivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarSerVivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EliminarSerVivo)
                .addGap(265, 265, 265))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(EliminarSerVivo)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Eliminar Programa", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        CBProgramas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBProgramasItemStateChanged(evt);
            }
        });

        TablaDatosClau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Puntuacion", "Año de lanzamiento", "Tipo", "Género"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TablaDatosClau);

        jLabel11.setText("Programas");

        GuardarArchivo.setText("Guardar Archivo");
        GuardarArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarArchivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(CBProgramas, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(268, 268, 268)
                                .addComponent(jLabel11))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(GuardarArchivo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBProgramas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GuardarArchivo)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Guardar Archivo", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        TextAreaArchivo.setColumns(20);
        TextAreaArchivo.setRows(5);
        jScrollPane3.setViewportView(TextAreaArchivo);

        CargarArchivo.setText("Cargar Archivo");
        CargarArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CargarArchivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(CargarArchivo)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(CargarArchivo)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Abrir Archivo", jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarSerVivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarSerVivoMouseClicked
        // TODO add your handling code here:
        String nombre, tipo, genero;
        int puntuacion, años;
        try {
            nombre = Nombre_Programa.getText();
            puntuacion = Integer.parseInt(Puntuacion.getText());
            años = Integer.parseInt(Año_Lanzamiento.getText());
            tipo = Tipodeprograma.getSelectedItem().toString();
            genero = Genero_programa.getSelectedItem().toString();
            if (puntuacion >= 1 && puntuacion <= 10) {
                Clau.add(new Clau(nombre, puntuacion, años, tipo, genero));
                Object[] newrow = {nombre, puntuacion, años, tipo, genero};
                DefaultTableModel modelo = (DefaultTableModel) TablaClauEliminar.getModel();
                modelo.addRow(newrow);
                TablaClauEliminar.setModel(modelo);
                TablaClauModificar.setModel(modelo);
                DefaultComboBoxModel cb = (DefaultComboBoxModel) CBProgramas.getModel();
                cb.addElement(new Clau(nombre, puntuacion, años, tipo, genero));
                CBProgramas.setModel(cb);
                //                Universo uni = new Universo();
                uni.getSeresvivos().add(new Clau(nombre, puntuacion, años, tipo, genero));
                System.out.println(uni.getSeresvivos());
                JOptionPane.showMessageDialog(this, "Programa exitosamente");
                Nombre_Programa.setText("");
                Puntuacion.setText("");
                Año_Lanzamiento.setText("");
                Tipodeprograma.setSelectedIndex(0);
                Genero_programa.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(this, "¡La puntuación debe ser de 1 a 10!");
                Nombre_Programa.setText("");
                Puntuacion.setText("");
                Año_Lanzamiento.setText("");
                Tipodeprograma.setSelectedIndex(0);
                Genero_programa.setSelectedIndex(0);
            } // Fin If
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        } // Fin Try Catch
    }//GEN-LAST:event_AgregarSerVivoMouseClicked

    private void ModificarAtributoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ModificarAtributoItemStateChanged
        // TODO add your handling code here:
        try {
            String nombre, planeta, raza;
            int poder, años;
            switch (ModificarAtributo.getSelectedIndex()) {
                case 0:
                    if (TablaClauModificar.getSelectedRow() >= 0) {
                        DefaultTableModel modelo = (DefaultTableModel) TablaClauModificar.getModel();
                        nombre = JOptionPane.showInputDialog("Ingrese el nuevo nombre: ");
                        modelo.setValueAt(nombre, TablaClauModificar.getSelectedRow(), 0);
                        TablaClauModificar.setModel(modelo);
                        TablaClauEliminar.setModel(modelo);
                        //                        Universo uni = new Universo(selectedFile.getPath());
                        //                        uni.CargarArchivo(TextAreaArchivo);
                        //                        int pos = TablaSeresVivosModificar.getSelectedRow();
                        //                        uni.getSeresvivos().get(pos).setNombre(nombre);
                        //                        uni.EscribirArchivo();
                    } // Fin If
                    break;
                case 1:
                    if (TablaClauModificar.getSelectedRow() >= 0) {
                        DefaultTableModel modelo1 = (DefaultTableModel) TablaClauModificar.getModel();
                        poder = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el nuevo poder: "));
                        modelo1.setValueAt(poder, TablaClauModificar.getSelectedRow(), 1);
                        TablaClauModificar.setModel(modelo1);
                        TablaClauEliminar.setModel(modelo1);
                        //                        Universo uni = new Universo(selectedFile.getPath());
                        //                        uni.CargarArchivo(TextAreaArchivo);
                        //                        int pos = TablaSeresVivosModificar.getSelectedRow();
                        //                        uni.getSeresvivos().get(pos).setPoder(poder);
                        //                        uni.EscribirArchivo();
                    } // Fin If
                    break;
                case 2:
                    if (TablaClauModificar.getSelectedRow() >= 0) {
                        DefaultTableModel modelo2 = (DefaultTableModel) TablaClauModificar.getModel();
                        años = Integer.parseInt(JOptionPane.showInputDialog("Ingrese los nuevos años: "));
                        modelo2.setValueAt(años, TablaClauModificar.getSelectedRow(), 2);
                        TablaClauModificar.setModel(modelo2);
                        TablaClauEliminar.setModel(modelo2);
                        //                        Universo uni = new Universo(selectedFile.getPath());
                        //                        uni.CargarArchivo(TextAreaArchivo);
                        //                        int pos = TablaSeresVivosModificar.getSelectedRow();
                        //                        uni.getSeresvivos().get(pos).setAños(años);
                        //                        uni.EscribirArchivo();
                    } // Fin If
                    break;
                case 3:
                    if (TablaClauModificar.getSelectedRow() >= 0) {
                        DefaultTableModel modelo3 = (DefaultTableModel) TablaClauModificar.getModel();
                        planeta = JOptionPane.showInputDialog("Ingrese el nuevo planeta: ");
                        modelo3.setValueAt(planeta, TablaClauModificar.getSelectedRow(), 3);
                        TablaClauModificar.setModel(modelo3);
                        TablaClauEliminar.setModel(modelo3);
                        //                        Universo uni = new Universo(selectedFile.getPath());
                        //                        uni.CargarArchivo(TextAreaArchivo);
                        //                        int pos = TablaSeresVivosModificar.getSelectedRow();
                        //                        uni.getSeresvivos().get(pos).setPlaneta(planeta);
                        //                        uni.EscribirArchivo()
                    } // Fin If
                    break;
                case 4:
                    if (TablaClauModificar.getSelectedRow() >= 0) {
                        DefaultTableModel modelo4 = (DefaultTableModel) TablaClauModificar.getModel();
                        int opcion = Integer.parseInt(JOptionPane.showInputDialog("1. Humano" + "\n" + "2. Amanto" + "\n" + "Ingrese la nueva raza: "));
                        switch (opcion) {
                            case 1:
                                raza = "Humano";
                                modelo4.setValueAt(raza, TablaClauModificar.getSelectedRow(), 4);
                                TablaClauModificar.setModel(modelo4);
                                TablaClauEliminar.setModel(modelo4);
                                //                        Universo uni = new Universo(selectedFile.getPath());
                                //                        uni.CargarArchivo(TextAreaArchivo);
                                //                        int pos = TablaSeresVivosModificar.getSelectedRow();
                                //                        uni.getSeresvivos().get(pos).setRaza(raza);
                                //                        uni.EscribirArchivo()
                                break;
                            case 2:
                                raza = "Amanto";
                                modelo4.setValueAt(raza, TablaClauModificar.getSelectedRow(), 4);
                                TablaClauModificar.setModel(modelo4);
                                TablaClauEliminar.setModel(modelo4);
                                //                        Universo uni = new Universo(selectedFile.getPath());
                                //                        uni.CargarArchivo(TextAreaArchivo);
                                //                        int pos = TablaSeresVivosModificar.getSelectedRow();
                                //                        uni.getSeresvivos().get(pos).setRaza(raza);
                                //                        uni.EscribirArchivo()
                                break;
                            default:
                                JOptionPane.showMessageDialog(this, "Opcion no valida");
                        } // Fin Switch
                    } // Fin If
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Ocurrio un error y no se pudo modificar");
            } // Fin Switch
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        } // Fin Try Catch
    }//GEN-LAST:event_ModificarAtributoItemStateChanged

    private void EliminarSerVivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarSerVivoMouseClicked
        // TODO add your handling code here:
        try {
            if (TablaClauEliminar.getSelectedRow() >= 0) {
                DefaultTableModel modelo = (DefaultTableModel) TablaClauEliminar.getModel();
                modelo.removeRow(TablaClauEliminar.getSelectedRow());
                TablaClauEliminar.setModel(modelo);
                TablaClauModificar.setModel(modelo);
                // Se supone que deberia eliminar del archivo pero no lo hace :(
                //                Universo uni = new Universo(selectedFile.getPath());
                //                uni.CargarArchivo(TextAreaArchivo);
                //                int pos = TablaSeresVivosEliminar.getSelectedRow();
                //                uni.getSeresvivos().remove(pos);
                //                uni.EscribirArchivo();
            } // Fin If
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        } // Fin Try Catch
    }//GEN-LAST:event_EliminarSerVivoMouseClicked

    private void CBProgramasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBProgramasItemStateChanged
        // TODO add your handling code here:
        try {
            if (evt.getStateChange() == 2) {
                Clau sv = (Clau) CBProgramas.getSelectedItem();
                Object[] newrow = {sv.getNombre(), sv.getPuntuacion(), sv.getAños(), sv.getTipo(), sv.getGenero()};
                DefaultTableModel modelo = (DefaultTableModel) TablaDatosClau.getModel();
                modelo.addRow(newrow);
                TablaDatosClau.setModel(modelo);
            } // Fin If
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se mostraron los datos");
        } // Fin Try Catch
    }//GEN-LAST:event_CBProgramasItemStateChanged

    private void GuardarArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarArchivoMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modeloy = (DefaultTableModel) TablaDatosClau.getModel();
        if (modeloy.getRowCount() != 0) {
            if (selectedFile != null) {
                DefaultTableModel modelot = (DefaultTableModel) TablaDatosClau.getModel();
                String acum = "";
                for (int i = 0; i < modelot.getRowCount(); i++) {
                    for (int j = 0; j < modelot.getColumnCount(); j++) {
                        if (j == modelot.getColumnCount() - 1) {
                            acum += modelot.getValueAt(i, j);
                        } else {
                            acum += modelot.getValueAt(i, j) + "|";
                        } // Fin If
                    } // Fin For
                    acum += "\n";
                } // Fin For
                FileWriter fw;
                try {
                    fw = new FileWriter(selectedFile);
                    BufferedWriter bw = new BufferedWriter(fw);
                    bw.write(acum);
                    bw.flush();
                    JOptionPane.showMessageDialog(this, "¡Se han guardado los nuevos datos!");
                    bw.close();
                    fw.close();
                } catch (IOException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                } // Fin Try Catch
            } else {
                JFileChooser jfc = new JFileChooser("./");
                FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de Texto", "txt");
                jfc.setFileFilter(filtro);
                int seleccion = jfc.showSaveDialog(this);
                FileWriter fw = null;
                BufferedWriter bw = null;
                if (seleccion == JFileChooser.APPROVE_OPTION) {
                    try {
                        if (jfc.getFileFilter().getDescription().equals("Archivo de Texto")) {
                            selectedFile = new File(jfc.getSelectedFile().getPath() + ".txt");
                        } else {
                            selectedFile = jfc.getSelectedFile();
                        } // Fin If
                        fw = new FileWriter(selectedFile);
                        bw = new BufferedWriter(fw);
                        DefaultTableModel modelo = (DefaultTableModel) TablaDatosClau.getModel();
                        String acum = "";
                        for (int i = 0; i < modelo.getRowCount(); i++) {
                            for (int j = 0; j < modelo.getColumnCount(); j++) {
                                if (j == modelo.getColumnCount() - 1) {
                                    acum += modelo.getValueAt(i, j);
                                } else {
                                    acum += modelo.getValueAt(i, j) + "/";
                                } // Fin If
                            } // Fin For
                            acum += "\n";
                        } // Fin For
                        bw.write(acum);
                        bw.flush();
                        JOptionPane.showMessageDialog(this, "¡Se ha guardado exitosamente el nuevo archivo!");
                    } catch (Exception e) {
                        e.printStackTrace();
                    } // Fin Try Catch
                    try {
                        bw.close();
                        fw.close();
                    } catch (IOException io) {
                        io.printStackTrace();
                    } // Fin Try Catch
                } // Fin If
            } // Fin If
        } else {
            JOptionPane.showMessageDialog(this, "¡La tabla debe tener por lo menos 1 ser vivo!");
        }
    }//GEN-LAST:event_GuardarArchivoMouseClicked

    private void CargarArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CargarArchivoMouseClicked
        // TODO add your handling code here:
        claudilist u = new claudilist(selectedFile.getPath());
        u.CargarArchivo(TextAreaArchivo);
    }//GEN-LAST:event_CargarArchivoMouseClicked

    private void AgregarSerVivo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarSerVivo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarSerVivo1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarSerVivo;
    private javax.swing.JButton AgregarSerVivo1;
    private javax.swing.JFormattedTextField Año_Lanzamiento;
    private javax.swing.JFormattedTextField Año_Lanzamiento1;
    private javax.swing.JComboBox<String> CBProgramas;
    private javax.swing.JButton CargarArchivo;
    private javax.swing.JButton EliminarSerVivo;
    private javax.swing.JComboBox<String> Genero_programa;
    private javax.swing.JComboBox<String> Genero_programa1;
    private javax.swing.JButton GuardarArchivo;
    private javax.swing.JComboBox<String> ModificarAtributo;
    private javax.swing.JTextField Nombre_Programa;
    private javax.swing.JTextField Nombre_Programa1;
    private javax.swing.JFormattedTextField Puntuacion;
    private javax.swing.JFormattedTextField Puntuacion1;
    private javax.swing.JTable TablaClauEliminar;
    private javax.swing.JTable TablaClauModificar;
    private javax.swing.JTable TablaDatosClau;
    private javax.swing.JTextArea TextAreaArchivo;
    private javax.swing.JComboBox<String> Tipodeprograma;
    private javax.swing.JComboBox<String> Tipodeprograma1;
    private javax.swing.JDialog jD_Modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
static ArrayList<Clau> Clau = new ArrayList();
    static claudilist uni = new claudilist();
    File selectedFile = null;

}
